KS-1-4 a lot of space
bokki48/KotlinSprint pull request #4
Opened 2024-06-12 15:04 UTC by bokki48

2024-06-13 07:09 UTC, ievetrovdev requested changes

2024-06-13 07:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson1_task4.kt
> +    val age: Short = 27
Полагаю есть еще меньше тип, чем Short)

2024-06-13 07:35 UTC, bokki48 commented on src/main/kotlin/lesson_1/lesson1_task4.kt
> +    val age: Short = 27
Согласен))

2024-06-13 07:50 UTC, bokki48 commented on src/main/kotlin/lesson_1/lesson1_task4.kt
> +    val age: Short = 27
KS-2-1 случайно закоммитил

2024-06-14 04:36 UTC, ievetrovdev approved these changes

2024-06-14 05:41 UTC, merged